shared_preload_libraries = 'pg_stat_statements,auto_explain'
pg_stat_statements.track = 'all'
auto_explain.log_min_duration = '100ms'
auto_explain.log_analyze = on
auto_explain.log_buffers = on
track_io_timing = on
track_wal_io_timing = on
